<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\modules\crmItevebasa\models\InspeccionesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Inspecciones';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="inspecciones-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Inspecciones', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'Estacion',
            'Anyo',
            'InformeMecanica',
            'FechaInspeccion',
            'Matricula',
            //'Bastidor',
            //'FechaMatriculacion',
            //'Marca',
            //'TipoVehiculo',
            //'CodigoConstruccion',
            //'CodigoUtilizacion',
            //'ContrasenyaHomologacion',
            //'FechaProximaInspeccion',
            //'FechaUltimaDesfavorable',
            //'FechaPrimeraMatriculacion',
            //'CodigoPropietario',
            //'Reforma1',
            //'Reforma2',
            //'Reforma3',
            //'Reforma4',
            //'Reforma5',
            //'DNI',
            //'Nombre',
            //'Domicilio',
            //'Municipio',
            //'CodigoPostal',
            //'Telefono1',
            //'Telefono2',
            //'TipoMatricula',
            //'TipoInspeccion',
            //'FaseInspeccion',
            //'AntiguedadVehiculo',
            //'Tarifa',
            //'ConceptoSigno1',
            //'ConceptoImporte1',
            //'ConceptoIVA1',
            //'ConceptoSigno2',
            //'ConceptoImporte2',
            //'ConceptoIVA2',
            //'ConceptoSigno3',
            //'ConceptoImporte3',
            //'ConceptoIVA3',
            //'ConceptoSigno4',
            //'ConceptoImporte4',
            //'ConceptoIVA4',
            //'ConceptoSigno5',
            //'ConceptoImporte5',
            //'ConceptoIVA5',
            //'ConceptoSigno6',
            //'ConceptoImporte6',
            //'ConceptoIVA6',
            //'TipoCombustible',
            //'ResultadoInspeccion',
            //'NumeroFactura',
            //'FechaPagoTasas',
            //'Capitulo1',
            //'Unidad1',
            //'Defecto1',
            //'Subdefecto1',
            //'Gravedad1',
            //'Capitulo2',
            //'Unidad2',
            //'Defecto2',
            //'Subdefecto2',
            //'Gravedad2',
            //'Capitulo3',
            //'Unidad3',
            //'Defecto3',
            //'Subdefecto3',
            //'Gravedad3',
            //'Capitulo4',
            //'Unidad4',
            //'Defecto4',
            //'Subdefecto4',
            //'Gravedad4',
            //'Capitulo5',
            //'Unidad5',
            //'Defecto5',
            //'Subdefecto5',
            //'Gravedad5',
            //'Capitulo6',
            //'Unidad6',
            //'Defecto6',
            //'Subdefecto6',
            //'Gravedad6',
            //'Capitulo7',
            //'Unidad7',
            //'Defecto7',
            //'Subdefecto7',
            //'Gravedad7',
            //'Capitulo8',
            //'Unidad8',
            //'Defecto8',
            //'Subdefecto8',
            //'Gravedad8',
            //'Capitulo9',
            //'Unidad9',
            //'Defecto9',
            //'Subdefecto9',
            //'Gravedad9',
            //'Capitulo10',
            //'Unidad10',
            //'Defecto10',
            //'Subdefecto10',
            //'Gravedad10',
            //'Capitulo11',
            //'Unidad11',
            //'Defecto11',
            //'Subdefecto11',
            //'Gravedad11',
            //'Capitulo12',
            //'Unidad12',
            //'Defecto12',
            //'Subdefecto12',
            //'Gravedad12',
            //'Capitulo13',
            //'Unidad13',
            //'Defecto13',
            //'Subdefecto13',
            //'Gravedad13',
            //'Capitulo14',
            //'Unidad14',
            //'Defecto14',
            //'Subdefecto14',
            //'Gravedad14',
            //'Capitulo15',
            //'Unidad15',
            //'Defecto15',
            //'Subdefecto15',
            //'Gravedad15',
            //'Capitulo16',
            //'Unidad16',
            //'Defecto16',
            //'Subdefecto16',
            //'Gravedad16',
            //'Capitulo17',
            //'Unidad17',
            //'Defecto17',
            //'Subdefecto17',
            //'Gravedad17',
            //'Capitulo18',
            //'Unidad18',
            //'Defecto18',
            //'Subdefecto18',
            //'Gravedad18',
            //'Capitulo19',
            //'Unidad19',
            //'Defecto19',
            //'Subdefecto19',
            //'Gravedad19',
            //'Capitulo20',
            //'Unidad20',
            //'Defecto20',
            //'Subdefecto20',
            //'Gravedad20',
            //'Capitulo21',
            //'Unidad21',
            //'Defecto21',
            //'Subdefecto21',
            //'Gravedad21',
            //'Capitulo22',
            //'Unidad22',
            //'Defecto22',
            //'Subdefecto22',
            //'Gravedad22',
            //'Capitulo23',
            //'Unidad23',
            //'Defecto23',
            //'Subdefecto23',
            //'Gravedad23',
            //'Capitulo24',
            //'Unidad24',
            //'Defecto24',
            //'Subdefecto24',
            //'Gravedad24',
            //'Capitulo25',
            //'Unidad25',
            //'Defecto25',
            //'Subdefecto25',
            //'Gravedad25',
            //'Capitulo26',
            //'Unidad26',
            //'Defecto26',
            //'Subdefecto26',
            //'Gravedad26',
            //'FrenoServicioFIE1',
            //'FrenoServicioFDE1',
            //'FrenoServicioFIE2',
            //'FrenoServicioFDE2',
            //'FrenoServicioFIE3',
            //'FrenoServicioFDE3',
            //'FrenoServicioFIE4',
            //'FrenoServicioFDE4',
            //'FrenoSocorroFIE1',
            //'FrenoSocorroFDE1',
            //'FrenoSocorroFIE2',
            //'FrenoSocorroFDE2',
            //'FrenoSocorroFIE3',
            //'FrenoSocorroFDE3',
            //'FrenoSocorroFIE4',
            //'FrenoSocorroFDE4',
            //'FrenoEstacionamientoFIE1',
            //'FrenoEstacionamientoFDE1',
            //'FrenoEstacionamientoFIE2',
            //'FrenoEstacionamientoFDE2',
            //'FrenoEstacionamientoFIE3',
            //'FrenoEstacionamientoFDE3',
            //'FrenoEstacionamientoFIE4',
            //'FrenoEstacionamientoFDE4',
            //'EficaciaServicio',
            //'EficaciaEstacionamiento',
            //'EficaciaSocorro',
            //'EmisionesOpacidad',
            //'EmisionesCORalenti',
            //'EmisionesCOAcelerado',
            //'EmisionesLambda',
            //'SingoAlinenacionE1',
            //'AlinenacionE1',
            //'SingoAlinenacionE2',
            //'AlinenacionE2',
            //'Decelerometro',
            //'VelocidadLimitador',
            //'Tara',
            //'MMA',
            //'MMARemolque',
            //'EmailPropietario:email',
            //'Categoria',
            //'Kilometros',
            //'Euro',
            //'Trazabilidad',
            //'NumeroSerieFrenometro',
            //'NumeroSerieEquipoHumos',
            //'NumeroSerieAlineadora',
            //'NumeroSerieVelocimetro',
            //'NumeroSerieDecelerometro',
            //'NumeroSerieTacometro',
            //'NumeroSerieSonometro',
            //'NumeroSerieDinamometro',
            //'NumeroSerieBascula',
            //'Seccion',
            //'d_diaInspeccion',
            //'HoraFactura',
            //'HoraInicio',
            //'HoraImpresionInforme',
            //'Hora1',
            //'Hora2',
            //'Hora3',
            //'Hora4',
            //'Hora5',
            //'Hora6',
            //'Hora7',
            //'Hora8',
            //'Hora9',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>
